import TextField from "@budget/components/base/input/textField"
import Paragraph from "@budget/components/base/text/paragraph"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function TestPage() {
  return (
    <div>
      paragraph:
      <TextField />
      <Paragraph size={"xs"} element={"p"}>This is div paragraphy</Paragraph>
      <Paragraph size={"sm"} element={"p"}>This is P paragraphy</Paragraph>
      <Paragraph size={"md"} element={"p"}>This is P paragraphy</Paragraph>
      <Paragraph size={"lg"} element={"p"}>This is span paragraphy</Paragraph>

    </div>
  )
}
